### ISSUE TITLE
where to view the changes?

### ISSUE THREAD

**Issue by next-free** [tcfev/Atlas#32]
i changed the database and sent pull request, you accept it and merge it but nothing changed on the main repo so nothing changed on the live website. where can i see the changes? do you have temp dev edit website?
@armantorkzaban

**Comment by armantorkzaban** [comment]
The issue was that the data was being overwritten with false db content via a cron job. I disabled the job, updated the data, pushed the changes. It should now work properly. 
However, the moderator's edit functinality requires the db and the cron job. Therefore my todo is to update the db with corrected data.
This means DB is updated we will only edit the data via the website using our moderator accounts.

**Comment by next-free** [comment]
so i have to edit db on the website from today? if yes, can you give me an account for that?
@armantorkzaban
